repos:
-   repo: https://github.com/franalgaba/pre-commit-cairo
    rev: 5587e6184323929b4f73abca922a49055fe2375c  # Use the ref you want to point at
    hooks:
    -   id: cairo-lint
    -   id: cairo-format
