version: '3.9'

services:
  devnet:
    # this image tag has static seed,
    # therefore the accounts stay the same
    image: shardlabs/starknet-devnet:latest-arm-seed0

  proxy:
    build:
      dockerfile: Dockerfile.nginx
    depends_on:
      - devnet
    ports:
      - 80:80

  deploy:
    build:
      dockerfile: Dockerfile.local
    platform: linux/x86_64
    depends_on:
      - devnet
    env_file: ./devnet/dev.env
    restart: always
    volumes:
      - ./abi/:/carmine/abi/
      - ./build/:/carmine/build/
      - ./lib/:/carmine/lib/
      - ${PWD}/_current_vars.env:/carmine/_current_vars.env
