FROM python:3.9.6-bullseye

WORKDIR /carmine/

COPY requirements.txt ./

RUN pip install -r requirements.txt
COPY devnet/init.sh ./
COPY devnet/starknet_open_zeppelin_accounts.json /root/.starknet_accounts/starknet_open_zeppelin_accounts.json
RUN chmod +x ./init.sh

ENTRYPOINT ["./init.sh"]
CMD ["tail", "-f", "/dev/null"]
