FROM python:3.9.6-bullseye

WORKDIR /carmine/

COPY requirements.txt ./

RUN pip install -r requirements.txt
COPY devnet/starknet_open_zeppelin_accounts.json /root/.starknet_accounts/starknet_open_zeppelin_accounts.json

ENTRYPOINT ["python", "/carmine/devnet/init.py"]
CMD ["tail", "-f", "/dev/null"]
