version: '3.9'

services:
  devnet:
    image: shardlabs/starknet-devnet:latest-arm-seed0
    ports:
      - 5050:5050

  deploy:
    build:
      dockerfile: Dockerfile.local
    platform: linux/x86_64
    depends_on:
      - devnet
    env_file: ./devnet/dev.env
    restart: always
    volumes:
      - ./abi/:/carmine/abi/
      - ./build/:/carmine/build/
      - ./lib/:/carmine/lib/
      - ./devnet/:/carmine/devnet/
