["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src",
    "./lib/cairo_math_64x61/contracts/cairo_math_64x61",
    "contracts/",
    "./lib/cairo_contracts/src"
]

["protostar.contracts"]
amm = [
    "./contracts/amm.cairo",
    "./contracts/liquidity_pool.cairo",
    #"./contracts/main.cairo",
    "./contracts/initialize_amm.cairo",
]
lptoken = [
    "./contracts/lptoken.cairo"
]
#option_token = [
#    "./contracts/option_token.cairo"
#]
