[project]
protostar-version = "0.9.0"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "./lib/cairo_math_64x61/contracts/cairo_math_64x61",
    "contracts/",
    "contracts/core_amm/",
    "contracts/erc20_tokens/",
    "contracts/interfaces/",
    "contracts/core_amm/views_from_outside/",
    "contracts/governance/"
]

[contracts]
amm = [
    "./contracts/core_amm/amm.cairo",
    "./contracts/core_amm/liquidity_pool.cairo",
    "./contracts/core_amm/options.cairo",
    "./contracts/core_amm/state.cairo",
    "./contracts/core_amm/views_from_outside/view.cairo",
    "./contracts/core_amm/proxy_utils.cairo"
]
lptoken = ["contracts/erc20_tokens/lptoken.cairo"]
option_token = ["contracts/erc20_tokens/option_token.cairo"]
proxy = ["contracts/proxy_contract/proxy.cairo"]
governance = [
    "contracts/governance/proposals.cairo",
    "contracts/governance/upgrades.cairo"
]
governance_proxy = ["contracts/governance/proxy_contract_custom.cairo"]