[project]
protostar-version = "0.9.0"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "./lib/cairo_math_64x61/contracts/cairo_math_64x61",
    "contracts/",
    "contracts/erc20_tokens/",
    "contracts/interfaces/",
    "contracts/views_from_outside/"
]

[contracts]
amm = [
    "./contracts/amm.cairo",
    "./contracts/liquidity_pool.cairo",
    "./contracts/options.cairo",
    "./contracts/state.cairo",
    "./contracts/views_from_outside/view.cairo",
    "./contracts/proxy_utils.cairo"
]
lptoken = ["contracts/erc20_tokens/lptoken.cairo"]
option_token = ["contracts/erc20_tokens/option_token.cairo"]
proxy = ["contracts/proxy_contract/proxy.cairo"]
