["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
amm = [
    "./contracts/main.cairo",
    "./contracts/liquidity_pool.cairo"
]
lptoken = [
    "./contracts/lptoken.cairo"
]
