["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
amm = [
    "./contracts/amm.cairo",
    "./contracts/initialize_amm.cairo",
    "./contracts/option_pricing.cairo",
]
